# Generated by Django 5.2.3 on 2026-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0005_book_remove_post_category_remove_myuserprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='rr.category'),
        ),
    ]
